# write a program to input eight numbers from the user and display all the unique numbes(once)
s=set()
s1=int(input("Enter the first number:"))
s.add(s1)
s2=int(input("Enter the second number:"))
s.add(s2)
s3=int(input("Enter the third number:"))
s.add(s3)
s4=int(input("Enter the fourth number:"))
s.add(s4)
s5=int(input("Enter the fifth number:"))
s.add(s5)
s6=int(input("Enter the sixth number:"))
s.add(s6)
s7=int(input("Enter the seventh number:"))
s.add(s7)
s8=int(input("Enter the eigth number:"))
s.add(s8)

print("The set of all numbers where they will be unique is:",s)