name ="sonali is a GIRL" # WHITE SPACE MATTERS HERE .. IT WILL BE COUNTED AS A CHARACTER 
print(len(name))
print(name.endswith("RL"))
print(name.startswith("s")) 
print(name.startswith("S"))
print(name.capitalize())
print(name.lower())
print(name.upper())
print(name.title())
print(name.find("sonali"))
print(name.replace("sonali","SONALI"))
print(name.count("i"))
print(name.strip())
print(name.split())